### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Lex1182** [binarycrafts/ACRExtensions#10]
It doesn't work anymore...
Chrome gives me this error:
VM337:19 Uncaught TypeError: Cannot read property 'KindleReaderContextMenu' of null(…)

Something changed.  I'm sure a lot of people are going to want this fixed asap.

**Comment by tachim** [comment]
The entitlement is strong with this one

**Comment by Lex1182** [comment]
It's adblock causing the error. I turned it off and it works. It looks like the error still happens in incognito even if incognito is supposed to turn off extensions, only removing "enable" under extensions solves it. I had tried multiple computers, re-installed chrome but it still happened on all of them before I realized I had to uncheck "enable". I see other people on forums having issues with adblock and other scripts.  Entitled or not, I hope this helps if it happens to someone else :)
