### ISSUE TITLE
Question - not an issue

### ISSUE THREAD

**Issue by vantienhoven** [binarycrafts/ACRExtensions#9]
You write: "In your browser do an "Add bookmark" action on the Bookmarks Bar and enter "ACRExtensions" for the name and copy and paste the bookmarklet code from the raw source."

Question: In FF, when I use the 'add New Bookmark' function, I have the following options I can complete:
-Name
-Location
-Tags
-Keyword
-Description
And a tick box to 'Load this bookmark in the sidebar

So I can enter the name in the given options, but I'm not sure what to do with "and copy and paste the bookmarklet code from the raw source."

You write: "Once you have the bookmarklet set up you just need to click on it once right after the Amazon Cloud Read app is loaded."

Question: Do you mean I need to load the bookmark first and then in the same tab and browser window load the url to the Kindle cloud url?

Kind regards, Sacha

**Comment by mvberkum** [comment]
Just used it, you have to use the 'Location' option for firefox for the raw source. You can leave the rest empty. 
After that, you go to the Kindle cloud reader, and after loading the book you want, press the bookmark you just created. You will get a alert box that is activated. 
If you copy a text, there will be (next to 'highlight' and 'note') a new copy button. Sometimes I have to refresh to get it show. If you press that, you will get a popup with the text you can copy/paste.

**Comment by vantienhoven** [comment]
Hi,
It works now. And hope that the following image helps other people :)
![capture](https://cloud.githubusercontent.com/assets/2852393/9174788/f9aa2190-3f79-11e5-9391-a2f954b60e2b.PNG)

Thank you, Sacha
